import { v4 as uuidv4 } from "uuid"; 

function chillHop() { 
  return [ 
    { 
      name: "Sunrise Serenade", 
      cover: "https://naasongs.com.co/wp-content/uploads/2024/01/Devara-2024.jpg", 
      artist: " Harmony Harp", 
      audio: "https://t3.ftcdn.net/jpg/03/20/41/30/360_F_320413016_omSvNeOZw7UrPyMvCf95KTCKzt6WbHXG.jpg", 
      color: ["#205950", "#2ab3bf"], 
      id: uuidv4(), 
      active: true, 
    }, 
    { 
      name: "Urban Groove", 
      cover: "https://naasongs.com.co/wp-content/uploads/2024/01/Devara-2024.jpg", 
      artist: "Beatmaster B", 
      audio: "https://media.geeksforgeeks.org/wp-content/uploads/20231004184006/SoundHelix-Song-10.mp3", 
      color: ["#EF8EA9", "#ab417f"], 
      id: uuidv4(), 
      active: false, 
    }, 
    { 
      name: "Mystic Echo", 
      cover: "https://naasongs.com.co/wp-content/uploads/2024/01/Devara-2024.jpg", 
      artist: " Harmony Harp", 
      audio: "https://media.geeksforgeeks.org/wp-content/uploads/20231004185212/Jawan-Prevue-Theme.mp3", 
      color: ["#CD607D", "#c94043"], 
      id: uuidv4(), 
      active: false, 
    }, 
    { 
      name: "Mystic Echo", 
      cover: "https://naasongs.com.co/wp-content/uploads/2024/01/Devara-2024.jpg", 
      artist: " Harmony Harp", 
      audio: "https://media.geeksforgeeks.org/wp-content/uploads/20231004185212/Jawan-Prevue-Theme.mp3", 
      color: ["#CD607D", "#c94043"], 
      id: uuidv4(), 
      active: false, 
    }, 
    { 
      name: "Mystic Echo", 
      cover: "https://naasongs.com.co/wp-content/uploads/2024/01/Devara-2024.jpg", 
      artist: " Harmony Harp", 
      audio: "https://media.geeksforgeeks.org/wp-content/uploads/20231004185212/Jawan-Prevue-Theme.mp3", 
      color: ["#CD607D", "#c94043"], 
      id: uuidv4(), 
      active: false, 
    }, 
    { 
      name: "Mystic Echo", 
      cover: "https://naasongs.com.co/wp-content/uploads/2024/01/Devara-2024.jpg", 
      artist: " Harmony Harp", 
      audio: "https://media.geeksforgeeks.org/wp-content/uploads/20231004185212/Jawan-Prevue-Theme.mp3", 
      color: ["#CD607D", "#c94043"], 
      id: uuidv4(), 
      active: false, 
    }, 
    { 
      name: "Mystic Echo", 
      cover: "https://naasongs.com.co/wp-content/uploads/2024/01/Devara-2024.jpg", 
      artist: " Harmony Harp", 
      audio: "https://media.geeksforgeeks.org/wp-content/uploads/20231004185212/Jawan-Prevue-Theme.mp3", 
      color: ["#CD607D", "#c94043"], 
      id: uuidv4(), 
      active: false, 
    }, 
    { 
      name: "Mystic Echo", 
      cover: "https://naasongs.com.co/wp-content/uploads/2024/01/Devara-2024.jpg", 
      artist: " Harmony Harp", 
      audio: "https://media.geeksforgeeks.org/wp-content/uploads/20231004185212/Jawan-Prevue-Theme.mp3", 
      color: ["#CD607D", "#c94043"], 
      id: uuidv4(), 
      active: false, 
    }, 
    { 
      name: "Mystic Echo", 
      cover: "https://naasongs.com.co/wp-content/uploads/2024/01/Devara-2024.jpg", 
      artist: " Harmony Harp", 
      audio: "https://media.geeksforgeeks.org/wp-content/uploads/20231004185212/Jawan-Prevue-Theme.mp3", 
      color: ["#CD607D", "#c94043"], 
      id: uuidv4(), 
      active: false, 
    }, 
    { 
      name: "Mystic Echo", 
      cover: "https://naasongs.com.co/wp-content/uploads/2024/01/Devara-2024.jpg", 
      artist: " Harmony Harp", 
      audio: "https://media.geeksforgeeks.org/wp-content/uploads/20231004185212/Jawan-Prevue-Theme.mp3", 
      color: ["#CD607D", "#c94043"], 
      id: uuidv4(), 
      active: false, 
    }, 
    { 
      name: "Mystic Echo", 
      cover: "https://naasongs.com.co/wp-content/uploads/2024/01/Devara-2024.jpg", 
      artist: " Harmony Harp", 
      audio: "https://media.geeksforgeeks.org/wp-content/uploads/20231004185212/Jawan-Prevue-Theme.mp3", 
      color: ["#CD607D", "#c94043"], 
      id: uuidv4(), 
      active: false, 
    }, 
    { 
      name: "Mystic Echo", 
      cover: "https://naasongs.com.co/wp-content/uploads/2024/01/Devara-2024.jpg", 
      artist: " Harmony Harp", 
      audio: "https://media.geeksforgeeks.org/wp-content/uploads/20231004185212/Jawan-Prevue-Theme.mp3", 
      color: ["#CD607D", "#c94043"], 
      id: uuidv4(), 
      active: false, 
    }, 
    { 
      name: "Mystic Echo", 
      cover: "https://naasongs.com.co/wp-content/uploads/2024/01/Devara-2024.jpg", 
      artist: " Harmony Harp", 
      audio: "https://media.geeksforgeeks.org/wp-content/uploads/20231004185212/Jawan-Prevue-Theme.mp3", 
      color: ["#CD607D", "#c94043"], 
      id: uuidv4(), 
      active: false, 
    }, 
    { 
      name: "Mystic Echo", 
      cover: "https://naasongs.com.co/wp-content/uploads/2024/01/Devara-2024.jpg", 
      artist: " Harmony Harp", 
      audio: "https://media.geeksforgeeks.org/wp-content/uploads/20231004185212/Jawan-Prevue-Theme.mp3", 
      color: ["#CD607D", "#c94043"], 
      id: uuidv4(), 
      active: false, 
    }, 
    { 
      name: "Mystic Echo", 
      cover: "https://naasongs.com.co/wp-content/uploads/2024/01/Devara-2024.jpg", 
      artist: " Harmony Harp", 
      audio: "https://media.geeksforgeeks.org/wp-content/uploads/20231004185212/Jawan-Prevue-Theme.mp3", 
      color: ["#CD607D", "#c94043"], 
      id: uuidv4(), 
      active: false, 
    }, 
    { 
      name: "Mystic Echo", 
      cover: "https://naasongs.com.co/wp-content/uploads/2024/01/Devara-2024.jpg", 
      artist: " Harmony Harp", 
      audio: "https://media.geeksforgeeks.org/wp-content/uploads/20231004185212/Jawan-Prevue-Theme.mp3", 
      color: ["#CD607D", "#c94043"], 
      id: uuidv4(), 
      active: false, 
    }, 
    { 
      name: "Mystic Echo", 
      cover: "https://naasongs.com.co/wp-content/uploads/2024/01/Devara-2024.jpg", 
      artist: " Harmony Harp", 
      audio: "https://media.geeksforgeeks.org/wp-content/uploads/20231004185212/Jawan-Prevue-Theme.mp3", 
      color: ["#CD607D", "#c94043"], 
      id: uuidv4(), 
      active: false, 
    }, 
    { 
      name: "Mystic Echo", 
      cover: "https://naasongs.com.co/wp-content/uploads/2024/01/Devara-2024.jpg", 
      artist: " Harmony Harp", 
      audio: "https://media.geeksforgeeks.org/wp-content/uploads/20231004185212/Jawan-Prevue-Theme.mp3", 
      color: ["#CD607D", "#c94043"], 
      id: uuidv4(), 
      active: false, 
    }, 
    
  ]; 
} 

export default chillHop;
